# Generated by Django 5.1.3 on 2024-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='moralperson',
            name='role',
            field=models.CharField(choices=[('PHYSICAL', 'Personne Physique'), ('MORAL', 'Personne Morale'), ('INVESTOR', 'Investisseur'), ('ADMIN', 'Administrateur')], default='PHYSICAL', max_length=10),
        ),
    ]
