# Generated by Django 5.1.3 on 2024-12-10 14:07

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('tourism', 'Tourisme'), ('social', 'Social'), ('agriculture', 'Agriculture'), ('technology', 'Technologie')], max_length=50)),
                ('goal', models.DecimalField(decimal_places=2, help_text='Budget estimé en GNF', max_digits=15)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, help_text='Montant financé en GNF', max_digits=15)),
                ('location', models.CharField(help_text='Localisation du projet', max_length=255)),
                ('currency', models.CharField(default='GNF', help_text='Code de la monnaie (ex : USD, EUR, etc.)', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Taux de change par rapport au GNF', max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, editable=False, help_text='Budget en GNF après conversion', max_digits=15)),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminé'), ('upcoming', 'À venir')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
