# Generated by Django 5.1.3 on 2024-12-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PorteurProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.TextField()),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(upload_to='img_porteur')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='exchange_rate',
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Budget en GNF après conversion', max_digits=15, verbose_name='Budget en GNF'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='GNF', help_text='Code de la monnaie (ex : USD, EUR, etc.)', max_length=10, verbose_name='Monnaie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_funding',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant financé en GNF', max_digits=15, verbose_name='Montant financé'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.DecimalField(decimal_places=2, help_text='Budget estimé en GNF', max_digits=15, verbose_name='Objectif du projet (Budget)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Localisation du projet', max_length=255, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminé'), ('upcoming', 'À venir')], default='upcoming', max_length=20, verbose_name='Statut du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.porteurproject', verbose_name='Porteur de projet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.projectcategory', verbose_name='Categorie du projet'),
        ),
    ]
