# Generated by Django 5.1.3 on 2024-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_porteurproject_projectcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('GNF', 'GNF - Franc guinéen'), ('USD', 'USD - Dollar américain'), ('EUR', 'EUR - Euro'), ('XOF', 'XOF - Franc CFA')], default='GNF', help_text='Sélectionnez la monnaie pour le budget', max_length=3, verbose_name='Monnaie'),
        ),
    ]
