name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]
  # pull_request:
  #   branches: [ main ]

jobs:
  check_syntaxe:
    name: Check Code Syntax
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black
    # - name: Run Flake8
    #   run: flake8 .
    - name: Run Black
      run: black --check .

  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: [check_syntaxe]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/prices-capital:latest
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/prices-capital:latest
